# Generated by Django 4.1.5 on 2023-02-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('text', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='тайтл', max_length=150, verbose_name='заголовок')),
                ('slug', models.TextField(max_length=200, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['id'], 'verbose_name': 'Известные женщины', 'verbose_name_plural': 'Известные щенщины'},
        ),
    ]
