# Generated by Django 3.2.5 on 2021-07-15 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='contact',
            new_name='content',
        ),
    ]
