# Generated by Django 4.1.5 on 2023-02-26 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_group_alter_women_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='group',
            field=models.ForeignKey(default='aaa', on_delete=django.db.models.deletion.CASCADE, to='women.group'),
        ),
    ]
