# Generated by Django 4.0.4 on 2024-03-11 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_women_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
